In [1]:
import numpy as np
num_list = [1, 2, 3, 4, 5]
num_arr = np.array([1 ,2, 3, 4, 5])

In [ ]:
# repetation of the list
print(num_list * 2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [3]:
print(num_arr * 2)

[ 2  4  6  8 10]


In [ ]:
arr_1 = np.array([1.5, 2.3, 3.2, 4.1])
print(arr_1.dtype)

int32


In [ ]:
# arr.ndim
# arr.shape
# arr.size 
# arr.dtype

In [ ]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

In [7]:
arr.ndim

2

In [ ]:
arr.shape

# 2 rows and 3 columns

(2, 3)

In [9]:
arr.size

6

In [10]:
arr = np.array([10, 20, 30, 40, 50])
arr.shape


(5,)

In [11]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

In [12]:
arr_2d.shape

(2, 3)

In [17]:
arr_3d = np.array([[[1, 2],
                    [3, 4]], 
                   [[5, 6],
                    [7, 8]]]    )

In [15]:
arr_3d.shape

(2, 2, 2)

In [18]:
#zeros
arr_zeros = np.zeros(5)
arr_zeros

array([0., 0., 0., 0., 0.])

In [19]:
arr_zeros = np.zeros((2, 3))
arr_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
#ones
arr_ones = np.ones(5)
arr_ones

array([1., 1., 1., 1., 1.])

In [21]:
arr_full = np.full((3, 3), 4)
arr_full

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [23]:
arr_d  = np.arange(0, 8)
print(arr_d)

[0 1 2 3 4 5 6 7]


In [24]:
arrr_l = np.linspace(0, 10, 5)
print(arrr_l)

[ 0.   2.5  5.   7.5 10. ]


In [25]:
# indexing 

arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

In [26]:
arr[-1]

50

In [27]:
lst = [ 10 , 20 , [30, 40, 50] , 60]
lst[2][1]

40

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])



In [31]:
arr_2d.shape

(3, 3)

In [30]:
arr_2d[1,1]

5

In [ ]:
#slicing

Arr= np.array([10, 20, 30, 40, 50])

Arr[1:4]

array([20, 30, 40])

In [33]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])


arr[:, 0]

array([1, 4])

In [34]:
arr[0, :]

array([1, 2, 3])

In [35]:
arr[: , 0:2]

array([[1, 2],
       [4, 5]])

In [36]:
arr[0:2 , 0:2]

array([[1, 2],
       [4, 5]])

In [37]:
#Mathematical Operations

arr = np.array([1, 2, 3 , 4])



In [38]:
arr + 10 

array([11, 12, 13, 14])

In [39]:
arr * 10

array([10, 20, 30, 40])

In [40]:
arr **2 

array([ 1,  4,  9, 16])

In [41]:
a = np.array([1 ,2,3])
b = np.array([10, 20, 30])

print(a + b)

[11 22 33]


In [42]:
# Element wise multiplication
print(a * b)

[10 40 90]


In [43]:
A = np.array([[1 , 2],
              [3 ,4]])
B  = np.array([[5 , 6], 
               [7 ,8]])

In [44]:
print(A * B)

[[ 5 12]
 [21 32]]


In [45]:
A1 =np.array([1 , 2, 3])
A2 = np.array([[2, 4] , [5 , 6]])

A1 * A2

ValueError: operands could not be broadcast together with shapes (3,) (2,2) 

In [48]:
arr = np.array([10 , 20 , 30 , 40 , 50])

print(np.mean(arr))
print(np.median(arr))
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))

30.0
30.0
150
10
50
14.142135623730951


In [49]:
arr = np.array([[10 , 20 , 30],            
                [40 , 50 , 60] ,
                [70 , 80 , 90]   ])

In [50]:
np.sum(arr)

450

In [51]:
np.sum(arr, axis=0) 

array([120, 150, 180])

In [52]:
np.sum(arr, axis=1) 

array([ 60, 150, 240])

In [53]:
arr___ = np.array([10 , 20 , 30 , 40 , 50])

arr___>30


array([False, False, False,  True,  True])

In [54]:
arr___[arr___>30]

array([40, 50])

In [55]:
arr___[arr___ % 2 ==0]

array([10, 20, 30, 40, 50])

In [56]:
arr =np.array([ 1 , 7 , 10 , 15 , 20])
arr[arr% 2 ==0]

array([10, 20])

In [ ]:
# NOT 
# OR ----- one of the values is TRUE 
# AND --- both values are TRUE

In [57]:
arr___[(arr___ > 20) & (arr___ < 50)]

array([30, 40])

In [58]:
arr___[(arr___ > 20) | (arr___ < 50)]

array([10, 20, 30, 40, 50])

In [59]:
marks = np.array([90, 40, 75, 30, 85])

np.where(marks >= 50, "Pass", "Fail")

array(['Pass', 'Fail', 'Pass', 'Fail', 'Pass'], dtype='<U4')

In [61]:
arr = np.arange(1, 13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [62]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
arr.reshape(5 , 3)

ValueError: cannot reshape array of size 12 into shape (5,3)

In [64]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
arr_11 = np.array([[1, 2],
                  [3, 4]])

    
arr_11.flatten()

array([1, 2, 3, 4])

In [67]:
arr_11

array([[1, 2],
       [3, 4]])

In [68]:
np.random.randint(1 , 10)

6

In [ ]:
import numpy as np

scores = np.array([[80, 75 , 90],
                  [70, 85 , 80],
                  [90, 95 , 100]])


# Rows = Students
# columns = Subjects

#shape , mean(subjects ) , max , min  , grades > 90 , stdents avg > 80 ,
# + grade for each student  