In [ ]:
name = input('ente your name')
print('welcome',name)

In [ ]:
age = int(input('enter your age'))
print("Next year you will be", age)

In [ ]:
age =  int(input("enter your age"))
salary = int(input("enter your salary "))

print(age >= 18)
print(age == 21)
print(salary > 10000)
print(salary != 0)


In [ ]:
name = (input('input your name'))
age = int(input('input your age'))
salary = int(input('input your salary'))
if age < 18:
    print(' Access Denied') 

elif age >= 18 and salary >= 1000 :
    print('Welcome ', name)
    print('Premium Account ')
else :
    print('Welcome ', name)
    print('standard account ')


In [ ]:
for i in range(11) :
  print(i)

print('+++++++++++++++')

for i in range(0,11,2) :
  print(i)  

In [ ]:
name = [2, 3 ,98, 985, 98]

print(name[0])
print(name[-1])

name[2] = 6
print(name)

name.append(9)
print(name)

for x in name :
 print(x)


In [ ]:
# دالة للتحقق هل الرقم أولي أم لا
def check_prime(n):
    if n <= 1:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

# قراءة الرقم من المستخدم
num = int(input("Enter an integer: "))

# البحث عن أولي أكبر من الرقم المدخل
next_num = num + 1

while True:
    if check_prime(next_num):
        print("The next prime number is:", next_num)
        break
    next_num = next_num + 1

In [ ]:
number = int(input("Enter your secret number: "))

while True:
    try:
        guess = int(input("Enter your guess: "))
    except ValueError:
        print("Invalid input! Please enter a number.")
        continue

    if guess == number:
        print("Congratulations! You guessed the secret number", number)
        break
    elif number > guess:
        print("too low! try again")
    else:
        print("too high! try again")

In [ ]:
balance = 1000

while True:
 try:
    withdraw_amount = int(input("enter your amount"))

    if withdraw_amount <= balance :
        balance = balance - withdraw_amount
        print("successful  withdraw :", balance)
        break

    else:
        print("Insufficient balance! Try again.")   
 except :
    print("enter number")
       

In [2]:
number = int(input("inter your secrit number "))

while True:
 
 try: 
  guess = int(input("inter guess number"))

  if number == guess :
        print("congraturation")
        break

    
  if guess > number :
        print("too high !! try again")    
  else :
        print("too low ! try again")

       
    
 except:
     print("error ")
    


            

too low ! try again
too low ! try again
congraturation


In [4]:
import sys

for _ in iter(int, 1):  # دي طريقة في بايثون بتخلي for تلف للمالانهاية زي while True
    try:
        age = int(input("Enter your age: "))
        if age >= 18:
            print("Access granted!")
            break
        else:
            print("Too young!")
    except:
        print("Invalid age!")

Too young!
Too young!
Invalid age!
Access granted!


In [6]:
# حفظ بيانات الاتصال بالداتابيز في Tuple
db_connection_config = ("19", 5432, "analytics_db")

# القراءة منها عادي بالـ Index
host = db_connection_config[0]
port = db_connection_config[1]

print(f"Connecting to {host}:{port}")

# لو جربت تعدل فيها كده:
# db_connection_config[1] = 3306  ---> هيديك TypeError فوراً!

Connecting to 19:5432


In [ ]:
subject = ("math", "science", "lanauge")
numbers = {1, 2, 2, 3, 4, 4, 5}
info = {
    "name" : "youssef",
    "age"  : 32,
    "grade" : "good"
}

print(subject[0])
print(numbers)
print(info["name"])
info["grade"] =   "A+"
print(info)



math
{1, 2, 3, 4, 5}
youssef
{'name': 'youssef', 'age': 32, 'grade': '  A+'}


In [1]:
def say_hello():
    print("hello yusuf")

def favorite_language():
    print("python")

def line():
    print("-----------------")

line()
say_hello()
favorite_language()
line()

-----------------
hello yusuf
python
-----------------


In [ ]:
def multi(n1, n2):
    return n1+n2
مل

print(multi(5,3))

8


In [ ]:
def test(length, width):
    area = length + width
    primeter = 2 * (length + width)
    return area, primeter

area, perimter = test(5,8)
print("area :",area)
print("primter :",perimter)


area : 13
primter : 26


In [ ]:
marks = [50, 60, 70, 80, 90]
print(list(map(lambda x : x+5, marks)))

[55, 65, 75, 85, 95]


In [33]:
prices = [100, 250, 400, 50]
print(list(map(lambda x: x-(x*.2), prices)))


[80.0, 200.0, 320.0, 40.0]


In [36]:
numbers = [5, 10, 15, 20, 25, 30]
print(list(filter(lambda x : x> 15, numbers)
))

[20, 25, 30]


In [18]:
def factorial(n):
    if n == 0:
        return 1

    return n * factorial(n - 1)

factorial(1)

1

In [18]:
class student:
    def __init__(self,name, age, grade):
        self.name = name
        self.age = age
        self.grade = grade

    def welcome(self):
        print("hello")    

student1 = student("yousef",21,90)
student2 = student("salah",54,67)

student1.welcome()


hello


In [30]:
class BanckACCOUNT():
    def __init__(self, name, balance):
        self.name = name
        self.balance = balance
    def deposit(self, new):
        self.balance += new
        return self.balance


    def withdraw(self, new):
        self.balance -= new
        return self.balance
    

    def show_balance(self):
        print(f"your balance is {self.balance}")    


clint1 = BanckACCOUNT("ypusef", 100)
clint1.deposit(50)
clint1.withdraw(20)
clint1.show_balance()



your balance is 130


In [6]:
import numpy as np 
nums = np.array([1, 4.5, 4, 8 ,0])

#result = nums * 2
print(nums.dtype)

float64


In [ ]:
import numpy as np

scores = np.array([[80, 75, 90],
                   [70, 85, 80],
                   [90, 95, 100]])

shape_res = scores.shape
subjects_mean = scores.mean(axis=0)
max_val = scores.max()
min_val = scores.min()
high_grades = scores[scores > 90]
students_avg_gt_80 = scores.mean(axis=1) > 80
scores_plus_grade = scores + 1

print( shape_res)
print( subjects_mean)
print( max_val)
print( min_val)
print( high_grades)
print( students_avg_gt_80)
print( scores_plus_grade)

Shape: (3, 3)
Mean of subjects: [80. 85. 90.]
Max: 100
Min: 70
Grades > 90: [ 95 100]
Students avg > 80: [ True False  True]
Scores + 1:
 [[ 81  76  91]
 [ 71  86  81]
 [ 91  96 101]]


In [8]:
import numpy as np

scores = np.array([[80, 75, 90],
                   [70, 85, 80],
                   [90, 95, 100]])


print("Shape ", scores.shape)
print("the mean subject", scores.mean(axis=0))
print("the max is", np.max(scores))
print("the min is", np.min(scores))
print("the student avg > 90", scores.mean(axis=1) > 90)
print("the student +5", scores + 5)

Shape  (3, 3)
the mean subject [80. 85. 90.]
the max is 100
the min is 70
the student avg > 90 [False False  True]
the student +5 [[ 85  80  95]
 [ 75  90  85]
 [ 95 100 105]]


In [ ]:
def green(name):
    return "Hello " + name

>>>>>>>>>>>>>  OOP >>>>>>>>>

In [32]:
class DataPiple():
    def __init__(self, name, source, destination, records):
        self.n = name
        self.s = source
        self.d = destination
        self.r = records
    def show_info(self):
        print("pipeline :", self.n)    
        print("MySQL :", self.s)    
        print("Data Warehouse :", self.d) 
        print("records :", self.r)

    def add_records(self, new):
            self.n = new
            self.r += self.n
            return self.r

    def states(self, states):
         self.states = states
         if self.states == "running":
            self.states = "completed"  
            return self.states     
                      
pipeline = DataPiple("ggg", "iujkljlk", "iujij", 15000)
pipeline.show_info()          
pipeline.add_records(60)          
pipeline.states("running")          
        

pipeline : ggg
MySQL : iujkljlk
Data Warehouse : iujij
records : 15000


'completed'

In [ ]:
class DataEngineer :
    company = "datatech"
    def __init__(self, name, salary):
        self.name = name
        self.salary = salary
    def show_inf(self):
        print("name :", self.name)
        print("salary :", self.salary)
        print("company :", self.company)
    @classmethod
    def change_company(cls,new_company):
        cls.company = new_company  
        return cls.company 
e1 = DataEngineer("yy", 3444)
e2 = DataEngineer("uu", 3444)
e1.change_company("google")    
e1.show_inf()
e2.show_inf()

name : yy
salary : 3444
company : google
name : uu
salary : 3444
company : google


In [45]:
class Employee:
    def __init__(self, name, salary):
        self.name = name 
        self.salary = salary 
    def show_info(self):
        print(self.name)
        print(self.salary)


class DataEngineer(Employee):
        def __init__(self, name, salary, specialization):
            super().__init__( name, salary)

            self.s = specialization


        def show_info(self):
            super().show_info()
            print(self.s)

e1 = DataEngineer("me", 345, "jkhukj")    
e1.show_info()


me
345
jkhukj
